face/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]

face/face/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url



urlpatterns = [
    url('', include('face2.urls')),
    url(r'^text/', include('text.urls')),
    path('admin/', admin.site.urls),
]

face/text/forms.py
from django import forms
from text.models import ImageToText
from crispy_forms.helper import FormHelper
from django.forms.models import inlineformset_factory
from crispy_forms.layout import Layout,Field, Fieldset, ButtonHolder, Submit,Button, Div
from django.forms import CharField, Form, PasswordInput
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login
import requests
# class VideoForm(forms.ModelForm):
#     class Meta:
#         model= Videos
#         fields= ["title", "video"]



class ImageToTextForm(forms.ModelForm):

    def __init__(self,*args, **kwargs):
        super(ImageToTextForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = True
        self.helper = FormHelper()
        # instance = getattr(self, 'instance', None)
        # if instance and instance.pk:
        #   self.fields['countrycode'].widget.attrs['readonly'] = True
        self.helper.from_tag = False
        self.helper.disable_csrf = True
        self.helper.layout =Layout(
            Div(
                Div(Field('image'), css_class="col-md-6"),
                Div(Field('text'), css_class="col-md-6"),
                css_class='row'
            ),
        )
    class Meta:
        model = ImageToText
        fields =('image','text')
     


class LoginForm(forms.Form):
    user_name = forms.CharField(label="Enter Email or Number")
    password =  forms.CharField(widget=PasswordInput())

    def __init__(self,*args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)



    def clean(self):
        user_name = self.cleaned_data['user_name']
        password = self.cleaned_data['password']
        print(user_name,password,'bala')
        if user_name and password:
            user = authenticate(username=user_name, password=password)
            print(user)
            if user:
            #     if user.is_superuser:
            #         login(request, user)
                print('login')
            else:
                print('error')
                raise forms.ValidationError('')
        return user    

# class ContactForm(forms.Form):
#     postcode = forms.CharField(max_length=10)
    
#     def __init__(self, *args, **kwargs):
#         super(ContactForm, self).__init__(*args, **kwargs)

#     def clean(self):
#         import requests
#         postcode = self.cleaned_data.get('postcode')
#         if settings.ECOMM_COUNTRY == 'UK':
#             if not postcode:
#                 self.add_error('postcode','This field is required')
#             r = requests.get('https://api.postcodes.io/postcodes/%s/validate' % (postcode,))
#             print(r.json())
#             is_valid = r.json().get('result')
#             if not is_valid:
#                 raise forms.ValidationError("Invalid Postcode")
#         return postcode

face/face/templates/base.html
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<!-- Static assets -->
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <!-- <link rel="icon" type="image/png"          href="{% static 'assets/img/favicon.png'    %}"> -->
  <link rel="icon"  href="{% static 'assets/img/face_image_gif.gif' %}" style="border-radius: 318px 238px;width: 70px;height: 64px;box-shadow: 0px 0px 11px 2px black;">

  <title>
    Face  Dashboard Django - {% block title %}{% endblock %} | Creative-Tim
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  
  <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet">

{% comment %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.bootstrap4.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/select/1.3.1/css/select.bootstrap4.min.css" rel="stylesheet">
  <link href="https://editor.datatables.net/extensions/Editor/css/editor.bootstrap4.min.css" rel="stylesheet">
{% endcomment %}

  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'assets/css/black-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
<!-- added new -->
  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="">


  <div class="wrapper">
    
    {% include 'header.html' %}
{% comment %}

    {% include 'includes/sidebar.html' %}
{% endcomment %}
    <div class="main-panel">

{% comment %}
      {% include 'includes/navigation.html' %}
{% endcomment %}

      <!-- <div class="content"> -->

        {% block content %}{% endblock content %}

      <!-- </div> -->

{% comment %}
      {% include 'includes/footer.html' %}
{% endcomment %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

    </div>
    
  </div>
{% comment %}

  {% include 'includes/fixed-plugin.html' %}

  {% include 'includes/scripts.html' %}

  {% include 'includes/scripts-sidebar.html' %}
{% endcomment %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}
<script type="text/javascript">
  
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
  

//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}


</script>

  {% endblock javascripts %}

</body>

</html

face/face/templates/footer.html
<style type="text/css">
.zoom {
 transition: transform 0.5s;
}
.zoom:hover {
  transform: scale(2); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
</style>
<footer class="text-center text-white" style="background-color: #525f7f;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1 "
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f zoom fa-lg" fa-lg ></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter zoom fa-lg"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google zoom fa-lg"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram zoom fa-lg"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin zoom fa-lg"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-light m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github zoom fa-lg"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-light p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-light" href="">Bala Prajapati</a>
  </div>
  <!-- Copyright -->
</footer>

face/face/templates/header.html
{% load static %}
<style type="text/css">
.bala {
/*  width: 100px;
  height: 100px;
  background: red;*/
  position: relative;
  animation-name: mymove;
  animation-iteration-count: infinite;
  animation-duration: 10s;
}

@keyframes mymove {
  from {top: 0px;}
  to {top: 300px;}
}




body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  border-radius: 25px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #1E1E2F;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)} 
  to {-webkit-transform: scale(1)}
}
  
@keyframes animatezoom {
  from {transform: scale(0)} 
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
/*

 .blink {
        animation: blinker 0.6s linear infinite;
        color: #1c87c9;
        font-size: 30px;
        font-weight: bold;
        font-family: sans-serif;
      }
      @keyframes blinker {
        50% {
          opacity: 0;
        }
      }
      .blink-one {
        animation: blinker-one 1s linear infinite;
      }
      @keyframes blinker-one {
        0% {
          opacity: 0;
        }
      }*/
      .blink-two {
        animation: blinker-two 1.4s linear infinite;
      }
      @keyframes blinker-two {
        100% {
          opacity: 0;
        }
      }

.login_text{
  border-radius: 25px;
  background-color: #30283B;
  color: white;

}


.login_button{
  border-radius: 25px;
  background-color: #30283B;
  color: white;

}
</style>
<div>
<div class="row m-2 ">
    <div class="col-md-3">
        <a href="{% url 'home' %}">
            <img src="{% static '/images/face_image_gif.gif' %}" style="border-radius: 318px 238px;width: 70px;height: 64px; 
    box-shadow: 0px 0px 11px 2px black;">
        </a>
    </div>
    <div class="col-md-3 text-center">
        <h4>Face Recognization Using Django.</h4>
    </div>
    <!-- floating all names  -->
    {% comment %}
    <div class="col-md-3 mt-5 mb-5 text-center">
        {% for names in name %}
        <div class="bala" >{{names.name}}</div>

        {% endfor %}
    </div>
    {% endcomment %}
    <div class="col-md-6">
      
    <!-- <h2>Modal Login Form</h2> -->
{% if user.is_authenticated %}
<div class="row float-right">
    <div mb-2>
        <span class="blink-two text-success">{{user.username|title }}</span>
        <a href="{% url 'logout_view' %}" class="btn btn-warning ">Logout</a>
    </div>
</div>
{% else %}
<a href="{% url 'login' %}">Login a</a>
<a onclick="document.getElementById('id01').style.display='block'" class="btn btn-warning float-right">Login</a>
{% comment %}
    <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>
{% endcomment %}
{% endif %}
    <div id="id01" class="modal ">
      
      <form class="modal-content animate" action="{% url 'login' %}" method="post" style="max-width: 28% !important">
        {% csrf_token %}
        <div class="imgcontainer">
          <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal" style="color: #787F81;">&times;</span>
          <img src="img_avatar2.png" alt="Super Admin Login" class="avatar">
        </div>

        <div class="container">
          <label for="uname"><b class="text-center" style="text-align: center;">Username</b></label>
          <input type="text" class="login_text" placeholder="Enter Username" name="uname" required>
          {% if validation_error %}
          <span>{{validation_error}}</span>
          {% endif %}

          <label for="psw"><b>Password</b></label>
          <input type="password" class="login_text" placeholder="Enter Password" name="psw" required>
            
          <button type="submit" class="login_button" style="width: 50%;">Login</button>
          <label class="ml-5">
            <input type="checkbox" checked="checked" name="remember"> Remember me
          </label>
        </div>

        <div class="container" style="background-color:#f1f1f1">
          <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
          <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
      </form>
    </div>

    </div>
    </div>
    <div>
      {% if img_txt_%}
    <marquee>
       <h2 style="margin-bottom: 0px !important">
            Converted Image To Test
        </h2>
    </marquee>
    {% else %}
    {% if count_all_face%}
    <marquee>
        <h2 style="margin-bottom: 0px !important">
            Total Face Detected <span style="color: yellow;">{{count_all_face}}</span>
        </h2>
    </marquee>
    {% endif %}
    {% endif %}
    <div>
    </div>
</div>
</div>

face/face/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mb-5">
    <div class="text-center">
    	<a href="{% url 'face' %}">
	        <div class="mb-5">
	            <img src="{% static '/images/add_new_face.gif' %}" border=0 style="box-shadow: 16px 17px 45px 58px azure;margin-top: 91px;">
	        </div>
	    </a>
        <div class="mt-5 mb-5">
            <span class="" style="">
                <h3 style="color: black;margin-top: 70px;">Add New Face</h3>
            </span>
        </div>
    </div>
    <div class="text-center">
        <a href="{% url 'TrainImages' %}">
        <div class="m-5 center">
            {% comment %}
            <img src="{% static '/images/face_train_gif.gif' %}" border=0 style="box-shadow: -2px -9px 49px 41px black;">
            {% endcomment %}
            <video class="" preload="auto" muted="" border=0 style="box-shadow: 1px -13px 51px 20px #232324;border-radius: 11px;" loop="" playsinline="" autoplay="" src="https://cdn.dribbble.com/users/707385/videos/20060/25_5_1.mp4">
            </video>
        </div>
        </a>
        <div class="mt-5 mb-0">
            <span class="" style="color: white;">
                <h3>Train Your Image To Machine</h3>
            </span>
        </div>
    </div>
    <div class="text-center">
        <a href="{% url 'track_image' %}">
        <div class="mb-3 mt-5">
            <img src="{% static '/images/Face_recog.gif' %}" border=0 style="box-shadow: -2px -9px 49px 41px black;">
        </div>
        </a>
        <div class="mt-2 mb-0">
            <span class="" style="color: white;">
                <h3>Track Your Face</h3>
            </span>
        </div>
    </div>

    <div class="text-center" >
          <a class="btn btn-success" href="{% url 'read_csv' %}">See Attendence</a>
    </div>

    <div class="text-center" >
          <a class="btn btn-success" href="{% url 'imagetotext' %}">Convert Image to Text</a>
    </div>

    <div class="text-center" >
          <a class="btn btn-success" href="{% url 'typing_test' %}">Stop Watch</a>
    </div>
</div>
{% endblock content %}

  

face/face/templates/list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div>
 
{% for video in videos %}
<video width="500" height="500" controls >
<source src="{{video.video.url}}" type="video/mp4">
<b>{{video.title}}</b>
</video>
{% endfor %}
 
</div>
</body>
</html>

face/face/templates/list_2.html
{% extends 'base.html' %}
{% block content %}
<style type="text/css">
.pagination_ {
  display: flex;
  list-style: none;
}
.pagination_ li {
  flex: 1;
  border-radius: 3px;
}
.pagination li.active a {
  font-size: 17px;
  color: #C4C4C9;
}

</style>

{% for names in page_obj %}
    .....{{ names.name|upper }} {{names.user_id}}<br>

{% endfor %}
{% comment %}
<div class="pagination_">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endcomment %}


<div class="container">
  <ul class="pagination">
        {% if page_obj.has_previous %}
    <li class="mr-2">
            <!-- <a href="?page=1">&laquo; first</a> -->
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    </li>
        {% endif %}
    <li><a href="#">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
    <li class="ml-2">
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <!-- <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> -->
    </li>
        {% endif %}
  </ul>
</div>
{% endblock content %}

{% block javascripts %}

<script type="text/javascript">
$("li").click(function () {
  $(this).addClass("active").siblings().removeClass("active");
});
</script>
{% endblock javascripts %}

face/face/templates/list_page_img_to_txt.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<style type="text/css">
.zoom_ {
 transition: transform 0.5s;
}
.zoom_:hover {
  transform: scale(1.2); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
</style>
	<div class="m-3">
		<a class="btn " href="{% url 'home' %}">Home</a>
	</div>
<div class="m-5">
    <table class="table" id="data_table_">
        <thead>
            <tr class="ml-5">
                <th>Image</th>
                <th>Text</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for it in img_txt %}
            <tr>
                <td><img class="img-fluid zoom_ ml-5" id="{{it.image.url}}" alt="{{it.image.url}}" style="max-width: 50%;max-height: 20%;position: relative;" src="{{it.image.url}}"></td>
                <td>{{it.text}}</td>

                <td><a class="btn btn-warning" href="{% url 'delete_text' id=it.id %}">Delete</a></td>
            </tr>
            {% endfor%}
        </tbody>
    </table>
</div>



<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>
{% endblock content %}

{% block javascripts%}
<script type="text/javascript">
$(document).ready(function() {
    $('#data_table_').DataTable();
} );









var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption

{% for it in img_txt %}
// alert('{{it.id}}')
var img = document.getElementById('{{it.id}}');
{% endfor %}
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
  modal.style.display = "none";
}
</script>
{% endblock javascripts%}

face/face/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<style type="text/css">
  .errorlist{
    display: none;
  } 
  #id_user_name{
    border-radius: 5px;
  }
  #id_password{
    border-radius: 5px;
  }


.input-icons i {
            position: absolute;
        }
          
        .input-icons {
            width: 100%;
            margin-bottom: 10px;
        }
          
        .icon {
            padding: 23px;
            min-width: 40px;
        }
          
        .input-field {
            width: 100%;
            padding: 10px;
            text-align: center;
        }
        .icon_rpls{

            margin-left: -18px !important;
        }
      input[type=text], input[type=password] {
          width: 106% !important;
        }

.pass_icon {      
    float: right;
    margin-top: 23px;
  }
</style>
<div class="row " style="margin-top: 70px;">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 mt-5 d-flex justify-content-center">
        <span style="color: white;">
            <h2>Login</h2>
        </span>
    </div>
    <div class="col-md-4">
    </div>
</div>

<div class="row " style="margin-bottom: 400px; ">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="m-3">
                {% if form.errors %}
                <p style="color: red;">Your username and password didn't match. Please try again.</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
             <div class="input-icons">
              <i class="fa fa-user icon icon_rpls"></i>
                    {{form.user_name}}
                     <i class="fa fa-key icon icon_rpls">
                          </i>
{% comment %}
                    <a id="log_show_pwd" class="pass_icon "  onclick="show_password('id_password','log_show_pwd','log_hide_pwd')"><i class="fa fa-eye-slash show_password"></i></a>
{% endcomment %}
                    <a toggle="#id_password" class="field-icon toggle-password pass_icon"><i id="icon_add" class="fa fa-fw fa-eye  "></i></a>
                    {{form.password}}
                  <!-- <a toggle="#id_password" class="field-icon toggle-password pass_icon"><i class="fa fa-fw fa-eye "></i></a> -->
                  </div>
                    <div class="row mt-4 d-flex justify-content-center">
                            <input class="btn btn-secondary mr-3" type="submit" value="submit" />
                            <input class="btn btn-secondary ml-3" type="button" value="Cancel" onclick="window.history.go(-1);" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
</div>


{% endblock content %}
{% block javascripts %}
<script type="text/javascript">
  // function show_password(input_id, show_pwd_id, hide_pwd_id) {
  //   document.getElementById(input_id).type = "text";
  //   document.getElementById(show_pwd_id).addAttr('hidden');
  //   document.getElementById(hide_pwd_id).removeAttr('hidden');
  // }

  // function hide_password(input_id, show_pwd_id, hide_pwd_id) {
  //   alert(show_pwd_id+hide_pwd_id)
  //     document.getElementById(input_id).type = "password";
  //     document.getElementById(show_pwd_id).removeAttr('hidden');
  //     document.getElementById(hide_pwd_id).addAttr('hidden');
  // }


$(".toggle-password").click(function() {

  $(this).toggleClass("fa-eye fa-eye-slash");
  var input = $($(this).attr("toggle"));
  if (input.attr("type") == "password") {
    input.attr("type", "text");
  } else {
    input.attr("type", "password");
  }
});
</script>
{% endblock javascripts %}


{% comment %}
<div class="container">
    <div class="row">
            {{ form.user_name|as_crispy_field}}
        </div>
        <div class="col-md-3">
            {{ form.password|as_crispy_field}}
        </div>
    </div>
</div>





    <div class="row " style="margin-bottom: 400px;">
        <div class="col-md-8">
          <img src="{% static '/images/login_1.png' %}">
        </div>
        <div class="col-md-3 mt-5">
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}
            <form method="post">
                    {% csrf_token %}
                    {{form}}
                <button class="btn btn-success" type="submit">Login</button>
                <input class="btn btn-secondary" type="button" value="Cancel" onclick="window.history.go(-1);" />
            </form>
        </div>
  </div>
{% endcomment %}

face/face/templates/super_admin_dashboad.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

{% endblock content %}

face/face/templates/take_image.html
{% extends 'base.html' %}